// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAspNet.Data.Context;

#nullable disable

namespace TaskAspNet.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429080511_SeedForNotifications")]
    partial class SeedForNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAspNet.Data.Entities.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Acme Corporation"
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "TechStart Inc."
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "Global Solutions Ltd."
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.Consent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdvertisingCookies")
                        .HasColumnType("bit");

                    b.Property<bool>("AnalyticsCookies")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateGiven")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FunctionalCookies")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConsentGiven")
                        .HasColumnType("bit");

                    b.Property<bool>("MarketingCookies")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consent", "dbo");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.JobTitleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Designer"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Project Manager"
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberAddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            AddressType = "Home",
                            City = "New York",
                            MemberId = 1,
                            ZipCode = "12345"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            AddressType = "Work",
                            City = "New York",
                            MemberId = 1,
                            ZipCode = "54321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak Ave",
                            AddressType = "Home",
                            City = "Los Angeles",
                            MemberId = 2,
                            ZipCode = "67890"
                        },
                        new
                        {
                            Id = 4,
                            Address = "135 Pine Rd",
                            AddressType = "Home",
                            City = "Chicago",
                            MemberId = 3,
                            ZipCode = "13579"
                        },
                        new
                        {
                            Id = 5,
                            Address = "246 Maple St",
                            AddressType = "Work",
                            City = "Chicago",
                            MemberId = 3,
                            ZipCode = "97531"
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            JobTitleId = 1,
                            LastName = "Doe",
                            UserId = "user-1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            JobTitleId = 2,
                            LastName = "Smith",
                            UserId = "user-2"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.johnson@example.com",
                            FirstName = "Mike",
                            JobTitleId = 3,
                            LastName = "Johnson",
                            UserId = "user-3"
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberPhoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberPhones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MemberId = 1,
                            Phone = "555-0101",
                            PhoneType = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            MemberId = 1,
                            Phone = "555-0102",
                            PhoneType = "Work"
                        },
                        new
                        {
                            Id = 3,
                            MemberId = 2,
                            Phone = "555-0201",
                            PhoneType = "Mobile"
                        },
                        new
                        {
                            Id = 4,
                            MemberId = 3,
                            Phone = "555-0301",
                            PhoneType = "Mobile"
                        },
                        new
                        {
                            Id = 5,
                            MemberId = 3,
                            Phone = "555-0302",
                            PhoneType = "Work"
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationDismissalEntity", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId", "UserId");

                    b.ToTable("NotificationDismissals");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationTargetGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTargetGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All user-level notifications",
                            IsActive = true,
                            Name = "Users",
                            Roles = "User"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All admin-level notifications",
                            IsActive = true,
                            Name = "Administrators",
                            Roles = "Admin,SuperAdmin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "All client-level notifications",
                            IsActive = true,
                            Name = "Clients",
                            Roles = "Client"
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultMessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultMessageTemplate = "New member '{0}' has been created",
                            Description = "Fires when a new member is created",
                            IsActive = true,
                            Name = "MemberCreated",
                            TargetGroupId = 2
                        },
                        new
                        {
                            Id = 2,
                            DefaultMessageTemplate = "Member '{0}' has been updated",
                            Description = "Fires when a member is updated",
                            IsActive = true,
                            Name = "MemberUpdated",
                            TargetGroupId = 2
                        },
                        new
                        {
                            Id = 3,
                            DefaultMessageTemplate = "New project '{0}' has been created",
                            Description = "Fires when a new project is created",
                            IsActive = true,
                            Name = "ProjectCreated",
                            TargetGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            DefaultMessageTemplate = "Project '{0}' has been updated",
                            Description = "Fires when a project is updated",
                            IsActive = true,
                            Name = "ProjectUpdated",
                            TargetGroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            DefaultMessageTemplate = "Member '{0}' added to project '{1}'",
                            Description = "Fires when a member is added to a project",
                            IsActive = true,
                            Name = "MemberAddedToProject",
                            TargetGroupId = 2
                        },
                        new
                        {
                            Id = 6,
                            DefaultMessageTemplate = "Member '{0}' removed from project '{1}'",
                            Description = "Fires when a member is removed from a project",
                            IsActive = true,
                            Name = "MemberRemovedFromProject",
                            TargetGroupId = 2
                        },
                        new
                        {
                            Id = 7,
                            DefaultMessageTemplate = "New client '{0}' has been created",
                            Description = "Fires when a new client is created",
                            IsActive = true,
                            Name = "ClientCreated",
                            TargetGroupId = 3
                        },
                        new
                        {
                            Id = 8,
                            DefaultMessageTemplate = "Client '{0}' has been updated",
                            Description = "Fires when a client is updated",
                            IsActive = true,
                            Name = "ClientUpdated",
                            TargetGroupId = 3
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 50000.00m,
                            ClientId = 1,
                            Description = "Complete overhaul of company website",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Website Redesign",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Budget = 75000.00m,
                            ClientId = 2,
                            Description = "New iOS and Android app development",
                            EndDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mobile App Development",
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Budget = 100000.00m,
                            ClientId = 3,
                            Description = "Online store development",
                            EndDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "E-commerce Platform",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ProjectMemberEntity", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            MemberId = 1
                        },
                        new
                        {
                            ProjectId = 1,
                            MemberId = 2
                        },
                        new
                        {
                            ProjectId = 2,
                            MemberId = 2
                        },
                        new
                        {
                            ProjectId = 2,
                            MemberId = 3
                        },
                        new
                        {
                            ProjectId = 3,
                            MemberId = 1
                        },
                        new
                        {
                            ProjectId = 3,
                            MemberId = 3
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ProjectStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Started"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Completed"
                        });
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberAddressEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.ClientEntity", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskAspNet.Data.Entities.MemberEntity", "Member")
                        .WithMany("Addresses")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.JobTitleEntity", "JobTitle")
                        .WithMany("Member")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberPhoneEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.ClientEntity", "Client")
                        .WithMany("Phones")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskAspNet.Data.Entities.MemberEntity", "Member")
                        .WithMany("Phones")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationDismissalEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.NotificationEntity", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.NotificationTypeEntity", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationTypeEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.NotificationTargetGroupEntity", "TargetGroup")
                        .WithMany("NotificationTypes")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ProjectEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.ClientEntity", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskAspNet.Data.Entities.ProjectStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ProjectMemberEntity", b =>
                {
                    b.HasOne("TaskAspNet.Data.Entities.MemberEntity", "Member")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskAspNet.Data.Entities.ProjectEntity", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ClientEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.JobTitleEntity", b =>
                {
                    b.Navigation("Member");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.MemberEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationTargetGroupEntity", b =>
                {
                    b.Navigation("NotificationTypes");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.NotificationTypeEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TaskAspNet.Data.Entities.ProjectEntity", b =>
                {
                    b.Navigation("ProjectMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
